---
title: "Project"
format: html
editor: visual
---

## LOADING LIBRARIES

```{r}
library(dplyr)
library(quantmod)
library(tidyquant)
library(lubridate)
library(skimr)
library(tidyr)

```

Pass the Ticker to get the data

```{r}
one_ticker = tq_get("^GSPC", from = "2002-12-31", to = "2024-02-01")
one_ticker %>% 
  head()
```

```{r}
write.csv(one_ticker,"S&P500.csv")
```

```{r}
#Importing S&P data
sp_data <- read.csv("S&P500.csv", header = TRUE)

#Importing FOMC data
fomc_data <- read.csv("fomc_data.csv", header = TRUE)
str(fomc_data)
```

```{r}
#Selecting relevant columns (date and adjusted close price) in S&P data
sp_data_selected <- select(sp_data, date, adjusted)
sp_data_selected

#Standardizing date column formatting in both dataframes
sp_data_selected$date <- as.Date(sp_data_selected$date)
class(sp_data_selected$date)

fomc_data$date <- as.Date(fomc_data$date, format = "%B %d, %Y")
fomc_data$date
```

```{r}
#merging both data frames on day of press release
merged_data <- merge(fomc_data, sp_data_selected, by = "date", all.x = TRUE)
skim(merged_data)
```

```{r}
names(merged_data)
clean_data <- select(merged_data, date, release_text, adjusted)
clean_data
```

```{r}
#check for na's
sum(is.na(clean_data$adjusted))
```

```{r}
clean_data <- clean_data %>% 
  arrange(date)

# Fill NA with the next available price
clean_data <- clean_data %>%
  fill(adjusted, .direction = "up")
```

```{r}
#Creating csv file with cleaned data
write.csv(clean_data, "cleaned_data.csv", row.names=FALSE)
```

#next steps continued in a different document
